"""revert changes

Revision ID: 4814cf051737
Revises: ac3e2f090a82
Create Date: 2022-05-24 15:28:46.660688

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4814cf051737'
down_revision = 'ac3e2f090a82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('room', 'time_estimate')
    op.drop_column('room', 'time_started')
    op.add_column('topic', sa.Column('time_estimate', sa.Interval(), nullable=False))
    op.add_column('topic', sa.Column('time_started', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('topic', 'time_started')
    op.drop_column('topic', 'time_estimate')
    op.add_column('room', sa.Column('time_started', mysql.DATETIME(), nullable=False))
    op.add_column('room', sa.Column('time_estimate', mysql.DATETIME(), nullable=False))
    # ### end Alembic commands ###
