"""changed room and topic model

Revision ID: ac3e2f090a82
Revises: 
Create Date: 2022-05-24 15:27:31.959416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac3e2f090a82'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('room',
    sa.Column('code', sa.String(length=36), nullable=False),
    sa.Column('host', sa.String(length=64), nullable=True),
    sa.Column('time_started', sa.DateTime(), nullable=False),
    sa.Column('time_estimate', sa.Interval(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('topic',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('room_code', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['room_code'], ['room.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('room_code', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['room_code'], ['room.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('topic')
    op.drop_table('room')
    # ### end Alembic commands ###
